<?php
/**
 * Implements hook_theme() to add the template definition.
 **/

function contact_us_theme($existing, $type, $theme, $path) {
  $theme = [];
  $theme['contact_us_template'] = [
    'template' => 'contact-us-template',
    'variables' => [
      'button_contact' => NULL,
    ],
  ];
  return $theme;
}

/**
 * Implements hook_install().
 *
 * Creates some default entries on this module custom table.
 *
 * @see hook_install()
 *
 * @ingroup contact_us
 */
function contact_us_install() {
  $database = \Drupal::database();
  // Add a default entry.
  $fields = array(
    'email' => 'test@gmail.com',
    'title' => 'Test',
    'text' => 'Some test data',
  );
  $database->insert('contact_us')
    ->fields($fields)
    ->execute();
}

/**
 * Implements hook_schema().
 *
 * Defines the database tables used by this module.
 *
 * @see hook_schema()
 *
 * @ingroup contact_us
 */
function contact_us_schema() {
  $schema['contact_us'] = array(
    'description' => 'Stores contact_us data from form.',
    'fields' => array(
      'pid' => array(
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Primary Key: Unique person ID.',
      ),
      'email' => array(
        'type' => 'varchar',
        'length' => 30,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Mail of sender',
      ),
      'title' => array(
        'type' => 'varchar',
        'length' => 30,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Title of the massage',
      ),
      'text' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Text of the massage',
      ),
    ),
    'primary key' => array('pid'),
    'indexes' => array(
      'title' => array('title'),
      'email' => array('email'),
    ),
  );

  return $schema;
}